import os
import numpy as np
import skimage.io


# TODO: just pass global_positions to functions assemble_and_save / assemble_image

# def assemble_and_save_image(global_positions_filepath, images_dirpath, output_filepath):
def assemble_and_save_image(global_positions, images_dirpath, output_filepath):
    
    parent, fn = os.path.split(output_filepath)
    if not os.path.exists(parent) and parent != '':
        os.makedirs(parent)
        
    stitched_image = assemble_image(global_positions, images_dirpath)
                
    print('Saving stitched image to disk')
    skimage.io.imsave(output_filepath, stitched_image, plugin=None, tile=(1024, 1024), check_contrast=False)

    
def assemble_image(global_positions, images_dirpath):

    # if not os.path.exists(global_positions):
    #     raise RuntimeError('Missing global positions file: {}'.format(global_positions))

    # # load the global positions for each image
    # img_names = list()
    # pixel_x_position = list()
    # pixel_y_position = list()
    # with open(global_positions, 'r') as fh:
    #     for line in fh:
    #         line = line.strip()
    #         toks = line.split(';')

    #         # handle file name loading
    #         fn_tok = toks[0]
    #         fn = fn_tok.split(':')[1].strip()
    #         img_names.append(fn)

    #         # handle the position loading
    #         pos_tok = toks[2]
    #         pos_pair = pos_tok.split(':')[1].strip()
    #         pos_pair = pos_pair.replace(')', '')
    #         pos_pair = pos_pair.replace('(', '')
    #         pos_pairs = pos_pair.split(',')
    #         x = int(pos_pairs[0].strip())
    #         y = int(pos_pairs[1].strip())
    #         pixel_x_position.append(x)
    #         pixel_y_position.append(y)

    # print(pixel_x_position)

    # extract information needed for image stitching
    img_names = global_positions['file']
    pixel_x_position = global_positions['position_x']
    pixel_y_position = global_positions['position_y']
    
    # verify that all images exist
    if not os.path.exists(images_dirpath):
        raise RuntimeError('Images directory does not exist: {}'.format(images_dirpath))

    for fn in img_names:
        if not os.path.exists(os.path.join(images_dirpath, fn)):
            raise RuntimeError(f'Image {fn} expected based on global positions, but its missing from the image directory.')

    # compute how large of an output image will be required.
    first_tile = skimage.io.imread(os.path.join(images_dirpath, img_names[0]))
    tile_shape = first_tile.shape
    n_channels = 1
    if len(tile_shape) == 3:
        n_channels = tile_shape[2]
    tile_h = tile_shape[0]
    tile_w = tile_shape[1]

    stitched_img_h = tile_h + np.max(pixel_y_position)
    stitched_img_w = tile_w + np.max(pixel_x_position)

    # creating blank image
    print(f'Creating blank stitched image of size: ({stitched_img_h}, {stitched_img_w}, {n_channels})')
    if n_channels == 1:
        stitched_img = np.zeros((stitched_img_h, stitched_img_w), dtype=first_tile.dtype)
    else:
        stitched_img = np.zeros((stitched_img_h, stitched_img_w, n_channels), dtype=first_tile.dtype)

    for i in range(0, len(img_names)):
        fn = img_names[i]
        x = pixel_x_position[i]
        y = pixel_y_position[i]
        print('Img {}/{}. Placing {} at ({}, {})'.format(i+1, len(img_names), fn, x, y))
        tile = skimage.io.imread(os.path.join(images_dirpath, fn))
        if tile.shape != tile_shape:
            raise RuntimeError('All images must be the same shape. Image {} is {}, expected {}'.format(fn, tile.shape, tile_shape))
        if tile.dtype != first_tile.dtype:
            raise RuntimeError('Img {} has type: {}, expected {}.'.format(fn, tile.dtype, first_tile.dtype))

        if n_channels == 1:
            stitched_img[y:y+tile_h, x:x+tile_w] = tile
        else:
            stitched_img[y:y+tile_h, x:x+tile_w, :] = tile

    return stitched_img

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Script to assemble MIST stitched image')
    parser.add_argument('--global-positions-filepath', type=str, required=True, help='Filepath to the global positions file generated by MIST.')
    parser.add_argument('--images-dirpath', type=str, required=True, help='Dirpath (directory) where the source images exists.')
    parser.add_argument('--output-filepath', type=str, required=True, help='Filepath where to save the resulting stitched image.')

    args = parser.parse_args()
    global_positions_filepath = args.global_positions_filepath
    images_dirpath = args.images_dirpath
    output_filepath = args.output_filepath

    assemble_and_save_image(global_positions_filepath, images_dirpath, output_filepath)
